export const burgerItems = [
  {
    id: "1",
    name: "beef burger",
    price: 290,
    description: "",
    category: "burgers",
    hasOptions: true,
    hasCheeseSliceOption: true,
    hasDonerMeatOption: true,
    hasGratedCheeseOption: true,
    hasSaladOption: true,
    hasSaucesOption: true,
    hasSizeOption: true,
    sizeOptionDoublePrice: 50,
    sizeOptionTriplePrice: null,
  },
  {
    id: "2",
    name: "chicken burger",
    price: 300,
    description:
      "a delicious chicken burger. also available in double or triple!",
    category: "burgers",
    hasOptions: true,
    hasCheeseSliceOption: true,
    hasDonerMeatOption: true,
    hasGratedCheeseOption: true,
    hasSaladOption: true,
    hasSaucesOption: true,
    hasSizeOption: true,
    sizeOptionDoublePrice: 75,
    sizeOptionTriplePrice: 140,
  },
  {
    id: "3",
    name: "chicken fillet sandwich",
    price: 350,
    description: "",
    category: "burgers",
    hasOptions: true,
    hasSizeOption: false,
    hasCheeseSliceOption: true,
    hasGratedCheeseOption: true,
    hasSaladOption: true,
    hasSaucesOption: true,
  },
  {
    id: "4",
    name: "veggie burger",
    price: 280,
    description: "",
    category: "burgers",
    hasOptions: true,
    hasSizeOption: false,
    hasCheeseSliceOption: true,
    hasGratedCheeseOption: true,
    hasSaladOption: true,
  },
  {
    id: "5",
    name: "halloumi burger",
    price: 280,
    description: "",
    category: "burgers",
    hasOptions: true,
    hasSizeOption: false,
    hasCheeseSliceOption: true,
    hasDonerMeatOption: true,
    hasGratedCheeseOption: true,
    hasSaladOption: true,
    hasSaucesOption: true,
  },
  {
    id: "6",
    name: "chicken zinger burger",
    price: 310,
    description: "",
    category: "burgers",
    hasOptions: true,
    hasSizeOption: false,
    hasSaucesOption: true,
  },
];
