export const chickenItems = [
  {
    id: "7",
    name: "roast chicken breast",
    description: "",
    price: 330,
    category: "chicken",
    hasOptions: false,
  },
  {
    id: "8",
    name: "southern fried chicken ( 1 piece )",
    description: "",
    price: 170,
    category: "chicken",
    hasOptions: true,
    hasSaltAndVinegarOption: true,
  },
  {
    id: "8",
    name: "southern fried chicken ( 2 pieces )",
    description: "",
    price: 220,
    category: "chicken",
    hasOptions: true,
    hasSaltAndVinegarOption: true,
  },
  {
    id: "9",
    name: "southern fried chicken ( 3 pieces )",
    description: "",
    price: 270,
    category: "chicken",
    hasOptions: true,
    hasSaltAndVinegarOption: true,
  },
  {
    id: "10",
    name: "southern fried chicken ( 4 pieces )",
    description: "",
    price: 320,
    category: "chicken",
    hasOptions: true,
    hasSaltAndVinegarOption: true,
  },
  {
    id: "11",
    name: "6 chicken nuggets",
    description: "",
    price: 230,
    category: "chicken",
    hasOptions: false,
  },
  {
    id: "12",
    name: "9 chicken nuggets",
    description: "",
    price: 270,
    category: "chicken",
    hasOptions: false,
  },
  {
    id: "13",
    name: "12 chicken nuggets",
    description: "",
    price: 350,
    category: "chicken",
    hasOptions: false,
  },
  {
    id: "14",
    name: "20 chicken nuggets",
    description: "",
    price: 430,
    category: "chicken",
    hasOptions: false,
  },
  {
    id: "15",
    name: "6 chicken wings",
    description: "",
    price: 330,
    category: "chicken",
    hasOptions: true,
    hasSaltAndVinegarOption: true,
  },
  {
    id: "16",
    name: "6 chicken wings & chips",
    description: "",
    price: 380,
    category: "chicken",
    hasOptions: true,
    hasSaltAndVinegarOption: true,
  },
  {
    id: "17",
    name: "1 piece of southern fried chicken & chips",
    description: "",
    price: 330,
    category: "chicken",
    hasOptions: true,
    hasSaltAndVinegarOption: true,
    hasSaladOption: true,
  },
  {
    id: "18",
    name: "2 pieces of southern fried chicken & chips",
    description: "",
    price: 450,
    category: "chicken",
    hasOptions: true,
    hasSaltAndVinegarOption: true,
    hasSaladOption: true,
  },
  {
    id: "19",
    name: "3 pieces of southern fried chicken & chips",
    description: "",
    price: 520,
    category: "chicken",
    hasOptions: true,
    hasSaltAndVinegarOption: true,
    hasSaladOption: true,
  },
  {
    id: "20",
    name: "1 piece of southern fried chicken & doner meat",
    description: "",
    price: 450,
    category: "chicken",
    hasOptions: true,
    hasSaltAndVinegarOption: true,
    hasSaladOption: true,
  },
  {
    id: "21",
    name: "2 pieces of southern fried chicken & doner meat",
    description: "",
    price: 560,
    category: "chicken",
    hasOptions: true,
    hasSaltAndVinegarOption: true,
    hasSaladOption: true,
  },
  {
    id: "22",
    name: "3 pieces of southern fried chicken & doner meat",
    description: "",
    price: 620,
    category: "chicken",
    hasOptions: true,
    hasSaltAndVinegarOption: true,
    hasSaladOption: true,
  },
  {
    id: "23",
    name: "golden nugget meal",
    description: "9 nuggets, chips & naan bread,",
    price: 400,
    category: "chicken",
    hasOptions: true,
    hasSaltAndVinegarOption: true,
    hasSaladOption: true,
    hasSaucesOption: true,
  },
  {
    id: "24",
    name: "golden fillet sandwich meal",
    description: "chicken fillet burger, chips & a can.",
    price: 400,
    category: "chicken",
    hasOptions: true,
    hasSaltAndVinegarOption: true,
    hasSaladOption: true,
    hasSaucesOption: true,
    hasChooseCanOption: true,
  },
];
