// exmaples
export const extrasItems = [
  {
    name: "tub of sauce",
    description: "",
    price: 70,
    hasSizeOption: true,
    sizeOptionMediumPrice: 50,
    sizeOptionLargePrice: 70,
    hasSaucesOption: true,
    numberOfSaucesAvailable: 1,
    category: "extras",
  },
  {
    name: "gravy",
    description: "",
    price: 120,
    hasSizeOption: true,
    sizeOptionMediumPrice: 0,
    sizeOptionLargePrice: 70,
    hasSaucesOption: false,
    numberOfSaucesAvailable: null,
    category: "extras",
  },
  {
    name: "mushy peas",
    description: "",
    price: 120,
    hasSizeOption: true,
    sizeOptionMediumPrice: 0,
    sizeOptionLargePrice: 20,
    hasSaucesOption: false,
    numberOfSaucesAvailable: null,
    category: "extras",
  },
  {
    name: "baked beans",
    description: "",
    price: 120,
    hasSizeOption: true,
    sizeOptionMediumPrice: 0,
    sizeOptionLargePrice: 20,
    hasSaucesOption: false,
    numberOfSaucesAvailable: null,
    category: "extras",
  },
];
